Tools to work with PC-lint Plus (#1)
* Modified gcclint and hll to work with PC-lint Plus
* Rename PCLINT_PATH to PCLP_PATH

diff --git a/tools/hll b/tools/hll
--- a/tools/hll
+++ b/tools/hll
@@ -2,21 +2,20 @@
 
 ##################################################
 # HLL wrapper script.
-# Put this script together with hll.pl in a 
+# Put this script together with hll.pl in a
 # directory that is listed in $PATH, eg. ~/bin.
 ##################################################
 
-if [ ! -d "$PCLINT_PATH" ]; then
-    echo "Please define \$PCLINT_PATH"
+if [ ! -d "$PCLP_PATH" ]; then
+    echo 'Please define $PCLP_PATH' >&2
     exit 1
 fi
 
-MSG_TXT_PATH="$PCLINT_PATH/msg.txt"
+MSG_TXT_PATH="$PCLP_PATH/msg.txt"
 
 if [ ! -f "$MSG_TXT_PATH" ]; then
-    echo "Cannot find $MSG_TXT_PATH"
+    echo "Cannot find $MSG_TXT_PATH" >&2
     exit 1
 fi
 
-hll.pl "$MSG_TXT_PATH" $*
-
+hll.pl "$MSG_TXT_PATH" "$@"
